# -*- coding: utf-8 -*-
"""Semana2-Clase2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-5HNo5rX6fgcUWV3WPLANsGmxgSglUd
"""

print('Texto a imprimir')
print('Impresion 1'); print('Impresion 2')
print('Renglon 1 \n Renglon 2')
print('Renglon 1 \nRenglon 2')

print ("Hola", "todos")
print("Hola mundo's")

print("hola",3) # Aca toma al 3 como string
print("hola"+"grupo")
print("hola"+" grupo")
#print("hola"+3) 
# Esto ultimo dara error pus no se puede concatenar dos tipos de datos distintos
#se resuelve haciendo: 
print("hola"+str(3))

print("grupo 11", end=";")
#las comas no se imprimen o se incluyen en la impresion de pantalla
#pero podemos hacerlo colocando separador 
print("Hola","grupo",11, sep=",")

print(7+5)


a=3.5
print(type(a))
b=str(a)
print(type(b))

a = 4 
b= 7
c = a+b
print("la suma es igual a: ", a+b)

print("/"+"n")

"""Impresion de Variables con f-string"""

titulo ="total = "
print(f"{titulo} 7+4")
print(f"7+4 ={a+b}")

print("Imprimir dos {} variables con formato {} {}".format(a,b,c))

print("Imprimir la suma total es {2}, de las variables {1} y {0}".format(a,b,c))
#recordemos que python toma los ordenes de 3 elementos como 0, 1 y 2

print("Prueba %i"%c) # i de integer 
print("flotante %0.4f"%4.55) # aca el cero es la cantidad de espacios antes del numero 
#y el 4 es la cantidad de posiciones decimales para el flotante
print("flotante %7.2f"%4.55)
print("flotante 0.4%f"%4.55)
print("flotante %.4f"%4.55)

"""Ejercicio"""

nombre = "Nelson"
apellido = "Camacho" 
print(f"{nombre } Camacho")
print(nombre + apellido) 
print("Edad: " + str(37))
print("Ciudad {} \nPrograma: {}".format("Bogota","Mintic"))



"""# Entrada de Datos"""

#help (input)

nombre_2 = input("Ingrese un numero cualquiera")
print(nombre_2)
print(type(nombre_2))

num = input("Ingresar un numero entero: ")
print (type(num))
#aca va amostrarlo como string cuando es un numero

#Podemos hacer esto al contrario
num = int(input("Ingresar un numero entero: ")) 
print(num, " es"); print(type(num))

#Tambien hay un comando para que Python reconozca automaticamente que tipo de dato esta ingresando
num = eval(input("Ingresar un numero entero: ")) 
print(num, " es"); print(type(num))
num = eval(input("Ingresar un numero entero: ")) 
print(num, " es"); print(type(num)) 
num = input("Ingresar un numero entero: ")
print(num, " es"); print(type(num))

import this

print("Calculemos el area de un cuadrado")
m=input("Ingrese la unidad de medida: ")
l=float(input("Ingrese la medida numerica del largo: "))
a=float(input("Ingrese la medida numerica del ancho: "))
print ("La medida del Area del cuadrado es: ", l*a, m,"2")
print ("La medida del Area del cuadrado es: ", l*a, m+"2") #mas natural
#Intentalo hacer con formato, queda mas bonito

"""# Operaciones"""


print("Al introducir 5/2 obtenemos: {}, {}".format(5/2,"que es la división usual"))

print("Al introducir 5//2 obtenemos: {}, {}".format(5//2,"que es la división entera"))

print("Al introducir 5%2 obtenemos: {}, {}".format(5/2,"que es el modulo de la division"))